using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;

namespace Foundry.Schema.Compiler.Exporters;

/// <summary>
/// Exporter that converts Kafka event streaming entities/DTOs into AsyncAPI 3.0.0 JSON specification.
/// </summary>
public static class AsyncApiExporter
{
    public static string ExportJson(SchemaModel schema)
    {
        var channels = new Dictionary<string, object>();
        var operations = new Dictionary<string, object>();
        var messages = new Dictionary<string, object>();

        var kafkaEntities = (schema.Entities ?? new List<Entity>())
            .Where(e => e.KafkaOutboxEnabled || !string.IsNullOrEmpty(e.KafkaTopic))
            .Select(e => new { e.Name, Topic = !string.IsNullOrEmpty(e.KafkaTopic) ? e.KafkaTopic : $"{e.Name.ToLowerInvariant()}-events" })
            .Concat(
                (schema.Dtos ?? new List<DtoModel>())
                    .Where(d => d.KafkaOutboxEnabled || !string.IsNullOrEmpty(d.KafkaTopic))
                    .Select(d => new { d.Name, Topic = !string.IsNullOrEmpty(d.KafkaTopic) ? d.KafkaTopic : $"{d.Name.ToLowerInvariant()}-events" })
            ).ToList();

        foreach (var target in kafkaEntities)
        {
            var channelKey = target.Topic.Replace("-", "_");
            channels[channelKey] = new
            {
                address = target.Topic,
                messages = new Dictionary<string, object>
                {
                    [target.Name + "Event"] = new { _ref = $"#/components/messages/{target.Name}EventMessage" }
                }
            };

            messages[target.Name + "EventMessage"] = new
            {
                name = target.Name + "Event",
                title = $"{target.Name} Kafka Domain Event",
                contentType = "application/json",
                payload = new
                {
                    type = "object",
                    properties = new
                    {
                        eventId = new { type = "string" },
                        eventType = new { type = "string" },
                        timestamp = new { type = "string", format = "date-time" },
                        payload = new { type = "object" }
                    }
                }
            };

            operations[target.Name + "Subscribe"] = new
            {
                action = "receive",
                channel = new { _ref = $"#/channels/{channelKey}" },
                summary = $"Consume domain events published on topic {target.Topic}"
            };

            operations[target.Name + "Publish"] = new
            {
                action = "send",
                channel = new { _ref = $"#/channels/{channelKey}" },
                summary = $"Publish transactional outbox events to topic {target.Topic}"
            };
        }

        var doc = new
        {
            asyncapi = "3.0.0",
            info = new
            {
                title = $"{schema.Namespace} Kafka Event AsyncAPI Spec",
                version = schema.Version ?? "1.0.0",
                description = "Auto-generated by Foundry Platform AsyncApiExporter"
            },
            channels = channels,
            operations = operations,
            components = new
            {
                messages = messages
            }
        };

        var json = JsonSerializer.Serialize(doc, new JsonSerializerOptions { WriteIndented = true });
        return json.Replace("_ref", "$ref");
    }
}
