using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;

namespace Foundry.Schema.Compiler.Exporters;

/// <summary>
/// Exporter that converts a Foundry domain schema into an OpenAPI 3.1.0 JSON specification.
/// </summary>
public static class OpenApiExporter
{
    public static string ExportJson(SchemaModel schema)
    {
        var paths = new Dictionary<string, object>();
        var componentsSchemas = new Dictionary<string, object>();

        if (schema.Entities != null)
        {
            foreach (var entity in schema.Entities)
            {
                var entityName = entity.Name;
                var entityLower = entityName.ToLowerInvariant();
                var routePath = $"/api/v1/{entityLower}";

                // Schema component
                var propertiesDict = new Dictionary<string, object>();
                foreach (var prop in entity.Properties)
                {
                    propertiesDict[prop.Name] = new
                    {
                        type = MapOpenApiType(prop.Type),
                        description = prop.IsKey ? "Primary Key" : null
                    };
                }

                componentsSchemas[entityName] = new
                {
                    type = "object",
                    properties = propertiesDict
                };

                // REST Endpoints
                paths[$"{routePath}"] = new
                {
                    get = new
                    {
                        summary = $"List all {entityName} records",
                        tags = new[] { entityName },
                        responses = new
                        {
                            _200 = new
                            {
                                description = "Success",
                                content = new
                                {
                                    application_json = new
                                    {
                                        schema = new { type = "array", items = new { _ref = $"#/components/schemas/{entityName}" } }
                                    }
                                }
                            }
                        }
                    },
                    post = new
                    {
                        summary = $"Create a new {entityName}",
                        tags = new[] { entityName },
                        requestBody = new
                        {
                            required = true,
                            content = new
                            {
                                application_json = new
                                {
                                    schema = new { _ref = $"#/components/schemas/{entityName}" }
                                }
                            }
                        },
                        responses = new
                        {
                            _201 = new { description = "Created" }
                        }
                    }
                };

                paths[$"{routePath}/{{id}}"] = new
                {
                    get = new
                    {
                        summary = $"Get {entityName} by ID",
                        tags = new[] { entityName },
                        parameters = new[]
                        {
                            new { name = "id", @in = "path", required = true, schema = new { type = "string" } }
                        },
                        responses = new
                        {
                            _200 = new { description = "Success" },
                            _404 = new { description = "Not Found" }
                        }
                    },
                    delete = new
                    {
                        summary = $"Delete {entityName} by ID",
                        tags = new[] { entityName },
                        parameters = new[]
                        {
                            new { name = "id", @in = "path", required = true, schema = new { type = "string" } }
                        },
                        responses = new
                        {
                            _204 = new { description = "No Content" }
                        }
                    }
                };
            }
        }

        var doc = new
        {
            openapi = "3.1.0",
            info = new
            {
                title = $"{schema.Namespace} API Specification",
                version = schema.Version ?? "1.0.0",
                description = "Auto-generated by Foundry Platform OpenApiExporter"
            },
            paths = paths,
            components = new
            {
                schemas = componentsSchemas
            }
        };

        var json = JsonSerializer.Serialize(doc, new JsonSerializerOptions { WriteIndented = true });
        return json.Replace("_200", "200").Replace("_201", "201").Replace("_204", "204").Replace("_404", "404").Replace("_ref", "$ref").Replace("application_json", "application/json");
    }

    private static string MapOpenApiType(string type)
    {
        return type.ToLowerInvariant() switch
        {
            "int" or "int32" or "long" or "int64" => "integer",
            "decimal" or "double" or "float" => "number",
            "bool" or "boolean" => "boolean",
            _ => "string"
        };
    }
}
