using System;
using System.Collections.Generic;
using System.Text;

namespace Foundry.Schema.Compiler.Generators;

/// <summary>
/// Generator that creates a strongly-typed .NET / C# Client SDK from a Foundry domain schema.
/// </summary>
public static class CsharpSdkGenerator
{
    public static string Generate(SchemaModel schema)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated C# Client SDK for " + schema.Namespace);
        sb.AppendLine("// Generated by Foundry Framework v1.0.0\n");

        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Json;");
        sb.AppendLine("using System.Threading.Tasks;\n");

        sb.AppendLine($"namespace {schema.Namespace}.Client;");

        if (schema.Entities != null)
        {
            foreach (var entity in schema.Entities)
            {
                sb.AppendLine($"\npublic class {entity.Name}Model");
                sb.AppendLine("{");
                foreach (var prop in entity.Properties)
                {
                    sb.AppendLine($"    public {prop.Type} {prop.Name} {{ get; set; }}");
                }
                sb.AppendLine("}");

                sb.AppendLine($"\npublic class {entity.Name}Client");
                sb.AppendLine("{");
                sb.AppendLine("    private readonly HttpClient _http;");
                sb.AppendLine($"    public {entity.Name}Client(HttpClient http) => _http = http;\n");

                sb.AppendLine($"    public async Task<List<{entity.Name}Model>?> GetAllAsync()");
                sb.AppendLine($"        => await _http.GetFromJsonAsync<List<{entity.Name}Model>>(\"/api/v1/{entity.Name.ToLowerInvariant()}\");\n");

                sb.AppendLine($"    public async Task<{entity.Name}Model?> GetByIdAsync(string id)");
                sb.AppendLine($"        => await _http.GetFromJsonAsync<{entity.Name}Model>($\"/api/v1/{entity.Name.ToLowerInvariant()}/{{id}}\");\n");

                sb.AppendLine($"    public async Task<{entity.Name}Model?> CreateAsync({entity.Name}Model model)");
                sb.AppendLine("    {");
                sb.AppendLine($"        var res = await _http.PostAsJsonAsync(\"/api/v1/{entity.Name.ToLowerInvariant()}\", model);");
                sb.AppendLine($"        return await res.Content.ReadFromJsonAsync<{entity.Name}Model>();");
                sb.AppendLine("    }\n");

                sb.AppendLine($"    public async Task DeleteAsync(string id)");
                sb.AppendLine($"        => await _http.DeleteAsync($\"/api/v1/{entity.Name.ToLowerInvariant()}/{{id}}\");");
                sb.AppendLine("}");
            }
        }

        return sb.ToString();
    }
}
