using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Foundry.Schema.Compiler.Generators;

/// <summary>
/// Generates a Python client for a Foundry domain schema.
/// </summary>
/// <remarks>
/// Every generated endpoint calls <c>RequireAuthorization()</c>, and this client sent no
/// <c>Authorization</c> header, so every call it made answered 401 — which <c>raise_for_status()</c>
/// then reported as an HTTP error rather than as "you did not authenticate". It also offered
/// <c>delete_*</c> for entities that declare no DELETE, and no <c>update_*</c> at all for the ones
/// that declare PUT. <see cref="SdkSurface"/> answers both questions for all three languages.
/// </remarks>
public static class PythonSdkGenerator
{
    public static string Generate(SchemaModel schema)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Auto-generated Python Client SDK for " + schema.Namespace);
        sb.AppendLine("# Generated by Foundry Framework v1.0.0\n");

        sb.AppendLine("import requests");
        sb.AppendLine("from typing import List, Dict, Any, Optional\n");

        sb.AppendLine("class FoundryClient:");
        sb.AppendLine("    \"\"\"Client for the generated API.");
        sb.AppendLine("");
        sb.AppendLine("    Every endpoint requires an authenticated caller, so `token` is not optional");
        sb.AppendLine("    in practice: without it the API answers 401 to everything.");
        sb.AppendLine("    \"\"\"");
        sb.AppendLine("");
        sb.AppendLine("    def __init__(self, base_url: str, token: Optional[str] = None,");
        sb.AppendLine("                 tenant_id: Optional[str] = None):");
        sb.AppendLine("        self.base_url = base_url.rstrip('/')");
        sb.AppendLine("        self.headers: Dict[str, str] = {}");
        sb.AppendLine("        if token:");
        sb.AppendLine("            self.headers['Authorization'] = f'Bearer {token}'");
        sb.AppendLine("        if tenant_id:");
        sb.AppendLine("            self.headers['X-Tenant-ID'] = tenant_id\n");

        if (schema.Entities != null)
        {
            foreach (var entity in schema.Entities)
            {
                var name = entity.Name;
                var lower = name.ToLowerInvariant();

                // The route the application actually serves, from the one producer of that contract.
                // This emitted "/api/v1/{singular-lowercase}", so every call 404'd. `lower` is still
                // used for the Python method names, which are a naming choice rather than a contract.
                var route = ApiManifestGenerator.RouteFor(name);

                if (!SdkSurface.HasAnySurface(entity)) continue;

                sb.AppendLine($"    # {name} endpoints. Serves: {string.Join(", ", SdkSurface.MethodsFor(entity))}");

                if (SdkSurface.HasList(entity))
                {
                    sb.AppendLine($"    def get_all_{lower}(self) -> List[Dict[str, Any]]:");
                    sb.AppendLine($"        res = requests.get(f'{{self.base_url}}{route}', headers=self.headers)");
                    sb.AppendLine("        res.raise_for_status()");
                    sb.AppendLine("        return res.json()\n");
                }

                if (SdkSurface.HasGetById(entity))
                {
                    sb.AppendLine($"    def get_{lower}_by_id(self, item_id: str) -> Dict[str, Any]:");
                    sb.AppendLine($"        res = requests.get(f'{{self.base_url}}{route}/{{item_id}}', headers=self.headers)");
                    sb.AppendLine("        res.raise_for_status()");
                    sb.AppendLine("        return res.json()\n");
                }

                if (SdkSurface.HasCreate(entity))
                {
                    sb.AppendLine($"    def create_{lower}(self, data: Dict[str, Any]) -> Dict[str, Any]:");
                    sb.AppendLine($"        res = requests.post(f'{{self.base_url}}{route}', json=data, headers=self.headers)");
                    sb.AppendLine("        res.raise_for_status()");
                    sb.AppendLine("        return res.json()\n");
                }

                if (SdkSurface.HasUpdate(entity))
                {
                    sb.AppendLine($"    def update_{lower}(self, item_id: str, data: Dict[str, Any]) -> Dict[str, Any]:");
                    sb.AppendLine($"        res = requests.put(f'{{self.base_url}}{route}/{{item_id}}', json=data, headers=self.headers)");
                    sb.AppendLine("        res.raise_for_status()");
                    sb.AppendLine("        return res.json()\n");
                }

                if (SdkSurface.HasDelete(entity))
                {
                    sb.AppendLine($"    def delete_{lower}(self, item_id: str) -> None:");
                    sb.AppendLine($"        res = requests.delete(f'{{self.base_url}}{route}/{{item_id}}', headers=self.headers)");
                    sb.AppendLine("        res.raise_for_status()\n");
                }
            }
        }

        return sb.ToString();
    }
}
