using System.Text;

namespace Foundry.Schema.Compiler.Generators;

/// <summary>
/// Generator that creates a Python Client SDK using httpx/requests from a Foundry domain schema.
/// </summary>
public static class PythonSdkGenerator
{
    public static string Generate(SchemaModel schema)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Auto-generated Python Client SDK for " + schema.Namespace);
        sb.AppendLine("# Generated by Foundry Framework v1.0.0\n");

        sb.AppendLine("import requests");
        sb.AppendLine("from typing import List, Dict, Any, Optional\n");

        sb.AppendLine("class FoundryClient:");
        sb.AppendLine("    def __init__(self, base_url: str, tenant_id: Optional[str] = None):");
        sb.AppendLine("        self.base_url = base_url.rstrip('/')");
        sb.AppendLine("        self.headers = {'X-Tenant-ID': tenant_id} if tenant_id else {}\n");

        if (schema.Entities != null)
        {
            foreach (var entity in schema.Entities)
            {
                var name = entity.Name;
                var lower = name.ToLowerInvariant();

                sb.AppendLine($"    # {name} endpoints");
                sb.AppendLine($"    def get_all_{lower}(self) -> List[Dict[str, Any]]:");
                sb.AppendLine($"        res = requests.get(f'{{self.base_url}}/api/v1/{lower}', headers=self.headers)");
                sb.AppendLine("        res.raise_for_status()");
                sb.AppendLine("        return res.json()\n");

                sb.AppendLine($"    def get_{lower}_by_id(self, item_id: str) -> Dict[str, Any]:");
                sb.AppendLine($"        res = requests.get(f'{{self.base_url}}/api/v1/{lower}/{{item_id}}', headers=self.headers)");
                sb.AppendLine("        res.raise_for_status()");
                sb.AppendLine("        return res.json()\n");

                sb.AppendLine($"    def create_{lower}(self, data: Dict[str, Any]) -> Dict[str, Any]:");
                sb.AppendLine($"        res = requests.post(f'{{self.base_url}}/api/v1/{lower}', json=data, headers=self.headers)");
                sb.AppendLine("        res.raise_for_status()");
                sb.AppendLine("        return res.json()\n");

                sb.AppendLine($"    def delete_{lower}(self, item_id: str) -> None:");
                sb.AppendLine($"        res = requests.delete(f'{{self.base_url}}/api/v1/{lower}/{{item_id}}', headers=self.headers)");
                sb.AppendLine("        res.raise_for_status()\n");
            }
        }

        return sb.ToString();
    }
}
