using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Foundry.Schema.Compiler.Generators;

/// <summary>
/// Generates a Python client for a Foundry domain schema.
/// </summary>
/// <remarks>
/// <para>
/// Every generated endpoint calls <c>RequireAuthorization()</c>, and this client sent no
/// <c>Authorization</c> header, so every call it made answered 401 — which <c>raise_for_status()</c>
/// then reported as an HTTP error rather than as "you did not authenticate". It also offered
/// <c>delete_*</c> for entities that declare no DELETE, and no <c>update_*</c> at all for the ones
/// that declare PUT. <see cref="SdkSurface"/> answers both questions for all three languages.
/// </para>
/// <para>
/// Entity descriptions are emitted as comment lines adjacent to the existing entity group comment
/// because they describe the entity itself, not any individual operation. Python has no entity type in
/// this SDK surface, so a docstring on an operation would misrepresent the scope of the documentation.
/// Comments cannot be terminated by any content — no escaping is needed or applied.
/// </para>
/// <para>
/// Property descriptions are not representable in this SDK's current shape — it generates no model
/// types, so there is no natural place to attach them. If property documentation is needed, add model
/// types to the SDK surface.
/// </para>
/// </remarks>
public static class PythonSdkGenerator
{
    public static string Generate(SchemaModel schema)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Auto-generated Python Client SDK for " + schema.Namespace);
        sb.AppendLine("# Generated by Foundry Framework v1.0.0\n");

        sb.AppendLine("import requests");
        sb.AppendLine("from typing import List, Dict, Any, Optional\n");

        sb.AppendLine("class FoundryClient:");
        sb.AppendLine("    \"\"\"Client for the generated API.");
        sb.AppendLine("");
        sb.AppendLine("    Every endpoint requires an authenticated caller, so `token` is not optional");
        sb.AppendLine("    in practice: without it the API answers 401 to everything.");
        sb.AppendLine("    \"\"\"");
        sb.AppendLine("");
        sb.AppendLine("    def __init__(self, base_url: str, token: Optional[str] = None,");
        sb.AppendLine("                 tenant_id: Optional[str] = None):");
        sb.AppendLine("        self.base_url = base_url.rstrip('/')");
        sb.AppendLine("        self.headers: Dict[str, str] = {}");
        sb.AppendLine("        if token:");
        sb.AppendLine("            self.headers['Authorization'] = f'Bearer {token}'");
        sb.AppendLine("        if tenant_id:");
        sb.AppendLine("            self.headers['X-Tenant-ID'] = tenant_id\n");

        if (schema.Entities != null)
        {
            foreach (var entity in schema.Entities)
            {
                var name = entity.Name;
                var lower = name.ToLowerInvariant();

                // The route the application actually serves, from the one producer of that contract.
                // This emitted "/api/v1/{singular-lowercase}", so every call 404'd. `lower` is still
                // used for the Python method names, which are a naming choice rather than a contract.
                var route = ApiManifestGenerator.RouteFor(name);

                if (!SdkSurface.HasAnySurface(entity)) continue;

                sb.AppendLine($"    # {name} endpoints. Serves: {string.Join(", ", SdkSurface.MethodsFor(entity))}");

                // Emit entity description as comment lines if authored in IR
                if (!string.IsNullOrEmpty(entity.Description))
                {
                    EmitCommentLines(sb, entity.Description, 4);
                }

                if (SdkSurface.HasList(entity))
                {
                    sb.AppendLine($"    def get_all_{lower}(self) -> List[Dict[str, Any]]:");
                    sb.AppendLine($"        res = requests.get(f'{{self.base_url}}{route}', headers=self.headers)");
                    sb.AppendLine("        res.raise_for_status()");
                    sb.AppendLine("        return res.json()\n");
                }

                if (SdkSurface.HasGetById(entity))
                {
                    sb.AppendLine($"    def get_{lower}_by_id(self, item_id: str) -> Dict[str, Any]:");
                    sb.AppendLine($"        res = requests.get(f'{{self.base_url}}{route}/{{item_id}}', headers=self.headers)");
                    sb.AppendLine("        res.raise_for_status()");
                    sb.AppendLine("        return res.json()\n");
                }

                if (SdkSurface.HasCreate(entity))
                {
                    sb.AppendLine($"    def create_{lower}(self, data: Dict[str, Any]) -> Dict[str, Any]:");
                    sb.AppendLine($"        res = requests.post(f'{{self.base_url}}{route}', json=data, headers=self.headers)");
                    sb.AppendLine("        res.raise_for_status()");
                    sb.AppendLine("        return res.json()\n");
                }

                if (SdkSurface.HasUpdate(entity))
                {
                    sb.AppendLine($"    def update_{lower}(self, item_id: str, data: Dict[str, Any]) -> Dict[str, Any]:");
                    sb.AppendLine($"        res = requests.put(f'{{self.base_url}}{route}/{{item_id}}', json=data, headers=self.headers)");
                    sb.AppendLine("        res.raise_for_status()");
                    sb.AppendLine("        return res.json()\n");
                }

                if (SdkSurface.HasDelete(entity))
                {
                    sb.AppendLine($"    def delete_{lower}(self, item_id: str) -> None:");
                    sb.AppendLine($"        res = requests.delete(f'{{self.base_url}}{route}/{{item_id}}', headers=self.headers)");
                    sb.AppendLine("        res.raise_for_status()\n");
                }
            }
        }

        return sb.ToString();
    }

    /// <summary>
    /// Emits entity description as comment lines. Each line is prefixed with # and proper indentation.
    /// Strips \r to avoid control characters in output.
    /// </summary>
    private static void EmitCommentLines(StringBuilder sb, string? text, int indentSpaces)
    {
        if (string.IsNullOrWhiteSpace(text))
            return;

        var indent = new string(' ', indentSpaces);

        // Normalize newlines and strip \r to avoid control characters
        var normalized = text!.Replace("\r\n", "\n").Replace("\r", "\n");
        var lines = normalized.Split('\n');

        foreach (var line in lines)
        {
            // Trim trailing whitespace on each line, then emit as comment. A blank line becomes a
            // bare '#': '# ' would itself carry the trailing space that flake8 reports as W291,
            // so a description with a paragraph break would lint dirty in every generated SDK.
            var trimmed = line.TrimEnd();
            sb.AppendLine(trimmed.Length == 0 ? $"{indent}#" : $"{indent}# {trimmed}");
        }
    }
}
