using System;
using System.Collections.Generic;
using System.Text;

namespace Foundry.Schema.Compiler.Generators;

/// <summary>
/// Generator that creates a strongly-typed TypeScript Client SDK from a Foundry domain schema.
/// </summary>
public static class TypeScriptSdkGenerator
{
    public static string Generate(SchemaModel schema)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated TypeScript Client SDK for " + schema.Namespace);
        sb.AppendLine("// Generated by Foundry Framework v1.0.0\n");

        sb.AppendLine("export interface ApiConfig {");
        sb.AppendLine("  baseUrl: string;");
        sb.AppendLine("  tenantId?: string;");
        sb.AppendLine("  headers?: Record<string, string>;");
        sb.AppendLine("}\n");

        if (schema.Entities != null)
        {
            foreach (var entity in schema.Entities)
            {
                sb.AppendLine($"export interface {entity.Name} {{");
                foreach (var prop in entity.Properties)
                {
                    var propType = MapTypeScriptType(prop.Type);
                    var optional = prop.IsKey || prop.Type.EndsWith("?") ? "?" : "";

                    // Emitted exactly as declared. These were lower-cased, and the API applies no
                    // naming policy -- it serialises "FullName", not "fullname" -- so every field on
                    // every generated interface read back as undefined. TypeScript compiled it
                    // happily, which is why nothing caught it.
                    sb.AppendLine($"  {prop.Name}{optional}: {propType};");
                }
                sb.AppendLine("}\n");
            }
        }

        if (schema.Entities != null)
        {
            foreach (var entity in schema.Entities)
            {
                var name = entity.Name;

                // The route the application actually serves, from the one producer of that contract.
                // This emitted "/api/v1/{singular-lowercase}" -- the identical mistake that was found
                // and fixed in Studio's designer and playground, and never fixed here. Every SDK this
                // generator has ever produced, in all three languages, called URLs the running
                // application does not serve, so every request 404'd.
                var route = ApiManifestGenerator.RouteFor(name);

                sb.AppendLine($"export class {name}Client {{");
                sb.AppendLine("  constructor(private config: ApiConfig) {}\n");

                sb.AppendLine($"  async getAll(): Promise<{name}[]> {{");
                sb.AppendLine($"    const res = await fetch(`${{this.config.baseUrl}}{route}`, {{");
                sb.AppendLine("      headers: { 'X-Tenant-ID': this.config.tenantId || '', ...this.config.headers }");
                sb.AppendLine("    });");
                sb.AppendLine("    return await res.json();");
                sb.AppendLine("  }\n");

                sb.AppendLine($"  async getById(id: string): Promise<{name}> {{");
                sb.AppendLine($"    const res = await fetch(`${{this.config.baseUrl}}{route}/${{id}}`, {{");
                sb.AppendLine("      headers: { 'X-Tenant-ID': this.config.tenantId || '', ...this.config.headers }");
                sb.AppendLine("    });");
                sb.AppendLine("    return await res.json();");
                sb.AppendLine("  }\n");

                sb.AppendLine($"  async create(data: Partial<{name}>): Promise<{name}> {{");
                sb.AppendLine($"    const res = await fetch(`${{this.config.baseUrl}}{route}`, {{");
                sb.AppendLine("      method: 'POST',");
                sb.AppendLine("      headers: { 'Content-Type': 'application/json', 'X-Tenant-ID': this.config.tenantId || '', ...this.config.headers },");
                sb.AppendLine("      body: JSON.stringify(data)");
                sb.AppendLine("    });");
                sb.AppendLine("    return await res.json();");
                sb.AppendLine("  }\n");

                sb.AppendLine($"  async delete(id: string): Promise<void> {{");
                sb.AppendLine($"    await fetch(`${{this.config.baseUrl}}{route}/${{id}}`, {{");
                sb.AppendLine("      method: 'DELETE',");
                sb.AppendLine("      headers: { 'X-Tenant-ID': this.config.tenantId || '', ...this.config.headers }");
                sb.AppendLine("    });");
                sb.AppendLine("  }");
                sb.AppendLine("}\n");
            }
        }

        return sb.ToString();
    }

    private static string MapTypeScriptType(string type)
    {
        return type.ToLowerInvariant() switch
        {
            "int" or "int32" or "long" or "decimal" or "double" or "float" => "number",
            "bool" or "boolean" => "boolean",
            "datetime" => "string",
            _ => "string"
        };
    }
}
