using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Foundry.Schema.Compiler.Generators;

/// <summary>
/// Generates a typed TypeScript client for a Foundry domain schema.
/// </summary>
/// <remarks>
/// <para>
/// Every generated endpoint calls <c>RequireAuthorization()</c>, and this client sent no
/// <c>Authorization</c> header — so every call it made answered 401. It then passed the response
/// straight to <c>res.json()</c> without looking at the status, so that 401 body was parsed and
/// returned as though it were the entity the caller asked for. A failure that arrives typed as
/// success is the worst shape a client can have.
/// </para>
/// <para>
/// It also offered <c>delete</c> for entities that declare no DELETE, and no <c>update</c> at all
/// for the four in five that declare PUT. <see cref="SdkSurface"/> now answers both questions for
/// all three languages at once.
/// </para>
/// </remarks>
public static class TypeScriptSdkGenerator
{
    public static string Generate(SchemaModel schema)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated TypeScript Client SDK for " + schema.Namespace);
        sb.AppendLine("// Generated by Foundry Framework v1.0.0\n");

        sb.AppendLine("export interface ApiConfig {");
        sb.AppendLine("  baseUrl: string;");
        sb.AppendLine("  /** Bearer token. Every generated endpoint requires an authenticated caller. */");
        sb.AppendLine("  token?: string;");
        sb.AppendLine("  tenantId?: string;");
        sb.AppendLine("  headers?: Record<string, string>;");
        sb.AppendLine("}\n");

        sb.AppendLine("/** Thrown when the API answers with a non-success status. */");
        sb.AppendLine("export class FoundryApiError extends Error {");
        sb.AppendLine("  constructor(readonly status: number, readonly url: string, readonly body: string) {");
        sb.AppendLine("    super(`${url} answered ${status}: ${body}`);");
        sb.AppendLine("    this.name = 'FoundryApiError';");
        sb.AppendLine("  }");
        sb.AppendLine("}\n");

        sb.AppendLine("function buildHeaders(config: ApiConfig, json = false): Record<string, string> {");
        sb.AppendLine("  const headers: Record<string, string> = { ...config.headers };");
        sb.AppendLine("  if (json) headers['Content-Type'] = 'application/json';");
        sb.AppendLine("  if (config.token) headers['Authorization'] = `Bearer ${config.token}`;");
        sb.AppendLine("  if (config.tenantId) headers['X-Tenant-ID'] = config.tenantId;");
        sb.AppendLine("  return headers;");
        sb.AppendLine("}\n");

        sb.AppendLine("async function ensureOk(res: Response, url: string): Promise<Response> {");
        sb.AppendLine("  if (!res.ok) throw new FoundryApiError(res.status, url, await res.text().catch(() => ''));");
        sb.AppendLine("  return res;");
        sb.AppendLine("}\n");

        // Enums as string unions: the API reads and writes them by name, and a union costs nothing at
        // runtime. All of them used to be erased to `string`, so the values a caller got wrong were
        // exactly the ones the schema knew ("Engineering" for a TeamType, "Lead" for a SkillLevel).
        var enumNames = new HashSet<string>(StringComparer.Ordinal);
        RefuseNameCollisions(schema);
        foreach (var enumDef in schema.Enums ?? new List<Enum>())
        {
            if (enumDef.Values is not { Count: > 0 }) continue;
            if (!string.IsNullOrEmpty(enumDef.Description)) EmitJsDoc(sb, enumDef.Description, 0);
            sb.AppendLine($"export type {enumDef.Name} = {string.Join(" | ", enumDef.Values.Select(Quote))};\n");
            enumNames.Add(enumDef.Name);
        }

        foreach (var entity in schema.Entities ?? new List<Entity>())
        {
            var workflow = (schema.Workflows ?? new List<WorkflowModel>())
                .FirstOrDefault(w => w.Entity.Equals(entity.Name, StringComparison.OrdinalIgnoreCase));
            var properties = entity.Properties ?? new List<Property>();

            if (workflow is not null && workflow.States.Count > 0)
            {
                sb.AppendLine($"/** The states of the {workflow.Name} workflow. */");
                sb.AppendLine($"export type {entity.Name}WorkflowState = {string.Join(" | ", workflow.States.Select(s => Quote(s.Name)))};\n");
            }

            // The entity as the API returns it.
            if (!string.IsNullOrEmpty(entity.Description))
            {
                EmitJsDoc(sb, entity.Description, 0);
            }
            sb.AppendLine($"export interface {entity.Name} {{");

            // Every property is present on a read: the API serialises them all, a value never set as
            // its default. Marking them optional here made the one correct way to update -- read the
            // record, change a field, send it all back -- fail to type-check against the update body.
            foreach (var prop in properties)
            {
                EmitProperty(sb, prop, "", enumNames);
            }

            // What the server stamps and always returns. None of these is an IR property, so this
            // used to omit them all -- and a PUT that does not echo Version is refused with 409, so the
            // only update that works could not be written without a cast.
            sb.AppendLine("  /** Optimistic-concurrency token. Send it back on update; a stale one is refused with 409. */");
            sb.AppendLine("  readonly Version: number;");
            sb.AppendLine("  readonly CreatedAtUtc: string;");
            sb.AppendLine("  readonly UpdatedAtUtc: string;");

            if (workflow is not null)
            {
                // Only a transition moves these; the API ignores them on create and update. A row
                // written before the server stamped the initial state on create still reads "".
                var stateType = workflow.States.Count > 0 ? $"{entity.Name}WorkflowState | ''" : "string";
                sb.AppendLine("  /** Set by the server: the initial state on create, then each transition. */");
                sb.AppendLine($"  readonly CurrentState: {stateType};");
                sb.AppendLine("  readonly WorkflowId: string;");
                sb.AppendLine("  readonly WorkflowVersion: string;");
            }

            sb.AppendLine("}\n");

            // What a caller sends. Separate from the read shape because the server owns the key, the
            // tenant and owner keys, Version's increment and the workflow fields; `Partial<T>` of the
            // read shape invited every one of them, and none of the fields that are actually required.
            if (SdkSurface.HasCreate(entity) || SdkSurface.HasUpdate(entity))
            {
                sb.AppendLine($"/** The body of a create: what the caller supplies. */");
                sb.AppendLine($"export interface {entity.Name}Create {{");
                foreach (var prop in SdkSurface.CallerProperties(entity))
                {
                    EmitProperty(sb, prop, SdkSurface.IsRequired(prop) ? "" : "?", enumNames);
                }
                sb.AppendLine("}\n");
            }

            if (SdkSurface.HasUpdate(entity))
            {
                // A PUT replaces the whole document, so a field left out is reset rather than kept:
                // every caller field is required, and so is the Version the caller read.
                sb.AppendLine("/** The body of an update. A PUT replaces the whole record, so every field is sent. */");
                sb.AppendLine($"export type {entity.Name}Update = Required<{entity.Name}Create> & {{ Version: number }};\n");
            }
        }

        foreach (var entity in schema.Entities ?? new List<Entity>())
        {
            if (!SdkSurface.HasAnySurface(entity)) continue;

            var name = entity.Name;

            // The route the application actually serves, from the one producer of that contract.
            // This emitted "/api/v1/{singular-lowercase}" -- the identical mistake found and fixed in
            // Studio, in the exporters and in the test generator, and each time missed here.
            var route = ApiManifestGenerator.RouteFor(name);

            sb.AppendLine($"/** Serves: {string.Join(", ", SdkSurface.MethodsFor(entity))} */");
            sb.AppendLine($"export class {name}Client {{");
            sb.AppendLine("  constructor(private config: ApiConfig) {}\n");

            if (SdkSurface.HasList(entity))
            {
                sb.AppendLine($"  async getAll(): Promise<{name}[]> {{");
                sb.AppendLine($"    const url = `${{this.config.baseUrl}}{route}`;");
                sb.AppendLine("    const res = await fetch(url, { headers: buildHeaders(this.config) });");
                sb.AppendLine("    return await (await ensureOk(res, url)).json();");
                sb.AppendLine("  }\n");
            }

            if (SdkSurface.HasGetById(entity))
            {
                sb.AppendLine($"  async getById(id: string): Promise<{name}> {{");
                sb.AppendLine($"    const url = `${{this.config.baseUrl}}{route}/${{id}}`;");
                sb.AppendLine("    const res = await fetch(url, { headers: buildHeaders(this.config) });");
                sb.AppendLine("    return await (await ensureOk(res, url)).json();");
                sb.AppendLine("  }\n");
            }

            if (SdkSurface.HasCreate(entity))
            {
                sb.AppendLine($"  async create(data: {name}Create): Promise<{name}> {{");
                sb.AppendLine($"    const url = `${{this.config.baseUrl}}{route}`;");
                sb.AppendLine("    const res = await fetch(url, {");
                sb.AppendLine("      method: 'POST',");
                sb.AppendLine("      headers: buildHeaders(this.config, true),");
                sb.AppendLine("      body: JSON.stringify(data)");
                sb.AppendLine("    });");
                sb.AppendLine("    return await (await ensureOk(res, url)).json();");
                sb.AppendLine("  }\n");
            }

            if (SdkSurface.HasUpdate(entity))
            {
                sb.AppendLine($"  async update(id: string, data: {name}Update): Promise<{name}> {{");
                sb.AppendLine($"    const url = `${{this.config.baseUrl}}{route}/${{id}}`;");
                sb.AppendLine("    const res = await fetch(url, {");
                sb.AppendLine("      method: 'PUT',");
                sb.AppendLine("      headers: buildHeaders(this.config, true),");
                sb.AppendLine("      body: JSON.stringify(data)");
                sb.AppendLine("    });");
                sb.AppendLine("    return await (await ensureOk(res, url)).json();");
                sb.AppendLine("  }\n");
            }

            if (SdkSurface.HasDelete(entity))
            {
                sb.AppendLine("  async delete(id: string): Promise<void> {");
                sb.AppendLine($"    const url = `${{this.config.baseUrl}}{route}/${{id}}`;");
                sb.AppendLine("    const res = await fetch(url, { method: 'DELETE', headers: buildHeaders(this.config) });");
                sb.AppendLine("    await ensureOk(res, url);");
                sb.AppendLine("  }\n");
            }

            sb.AppendLine("}\n");
        }

        return sb.ToString();
    }

    /// <summary>
    /// Emits a JSDoc comment, handling multi-line text and escaping `*/` to prevent comment termination.
    /// </summary>
    private static void EmitJsDoc(StringBuilder sb, string? text, int indentSpaces)
    {
        if (string.IsNullOrWhiteSpace(text))
            return;

        var indent = new string(' ', indentSpaces);
        var lines = text!.Replace("\r\n", "\n").Replace("\r", "\n").Split('\n');

        sb.AppendLine($"{indent}/**");
        foreach (var line in lines)
        {
            // Escape */ to *\/ to prevent comment termination
            var escaped = line.Replace("*/", "*\\/");
            sb.AppendLine($"{indent} * {escaped}");
        }
        sb.AppendLine($"{indent} */");
    }

    private static void EmitProperty(StringBuilder sb, Property prop, string optional, HashSet<string> enumNames)
    {
        if (!string.IsNullOrEmpty(prop.Description))
        {
            EmitJsDoc(sb, prop.Description, 2);
        }

        // Emitted exactly as declared. These were lower-cased, and the API applies no naming
        // policy -- it serialises "FullName", not "fullname" -- so every field on every
        // generated interface read back as undefined. TypeScript compiled it happily.
        var type = enumNames.Contains(prop.Type) ? prop.Type : MapTypeScriptType(prop.Type);
        sb.AppendLine($"  {prop.Name}{optional}: {type};");
    }

    /// <summary>
    /// Refuses a schema whose own names clash with the types generated beside them.
    /// </summary>
    /// <remarks>
    /// An enum named <c>OrderCreate</c> next to an entity <c>Order</c> would emit two declarations of
    /// one name, which TypeScript rejects in the consumer's build rather than here. Failing at
    /// generation names the clash; the alternative is a client that does not compile.
    /// </remarks>
    private static void RefuseNameCollisions(SchemaModel schema)
    {
        var declared = new HashSet<string>(StringComparer.Ordinal);
        foreach (var e in schema.Enums ?? new List<Enum>()) declared.Add(e.Name);
        foreach (var e in schema.Entities ?? new List<Entity>()) declared.Add(e.Name);

        foreach (var entity in schema.Entities ?? new List<Entity>())
        {
            foreach (var generated in new[] { entity.Name + "Create", entity.Name + "Update", entity.Name + "WorkflowState" })
            {
                if (declared.Contains(generated))
                    throw new InvalidOperationException(
                        $"The schema declares '{generated}', which the TypeScript SDK generates for entity '{entity.Name}'. Rename one of them.");
            }
        }
    }

    private static string Quote(string value) => "'" + value.Replace("\\", "\\\\").Replace("'", "\\'") + "'";

    private static string MapTypeScriptType(string type)
    {
        return type.ToLowerInvariant() switch
        {
            "int" or "int32" or "long" or "decimal" or "double" or "float" => "number",
            "bool" or "boolean" => "boolean",
            "datetime" => "string",
            "list<string>" => "string[]",
            _ => "string"
        };
    }
}
