using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace Foundry.Schema.Compiler
{
    /// <summary>
    /// Thrown when a schema value reaches the emitter that cannot be safely rendered as C#.
    /// </summary>
    /// <remarks>
    /// <see cref="SchemaValidator"/> is expected to catch these conditions first and report
    /// them as user-facing diagnostics. Reaching this exception means validation was skipped
    /// or has a gap, so it is deliberately fatal rather than best-effort: emitting the value
    /// anyway would splice attacker- or model-controlled text into generated source.
    /// </remarks>
    public sealed class UnsafeSchemaValueException : Exception
    {
        /// <summary>The diagnostic code describing the failure.</summary>
        public string Code { get; }

        /// <summary>Initialises the exception.</summary>
        public UnsafeSchemaValueException(string code, string message) : base($"{code}: {message}")
        {
            Code = code;
        }
    }

    /// <summary>
    /// Emission-safety primitives shared by every Foundry generator.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Foundry generates C# by string composition, which means every schema-supplied value
    /// is a potential injection site. Because the schema can be authored by a local AI model
    /// as well as by a human, values must be treated as untrusted input:
    /// </para>
    /// <list type="bullet">
    /// <item><description>Anything emitted in an identifier position goes through <see cref="Ident"/>.</description></item>
    /// <item><description>Anything emitted inside a string literal goes through <see cref="Lit"/>.</description></item>
    /// <item><description>Anything emitted as an attribute argument list goes through <see cref="TryParseAttribute"/>.</description></item>
    /// </list>
    /// </remarks>
    public static class CodeGen
    {
        /// <summary>
        /// Header prepended to every generated file. Marks the file as compiler output so
        /// analysers, style rules and reviewers skip it, and tells humans where to put code.
        /// </summary>
        public const string GeneratedHeader =
@"// <auto-generated/>
//
// This file was generated by the Foundry schema compiler. Do not edit it:
// your changes will be overwritten the next time the schema is compiled.
//
// To add hand-written logic, create a sibling partial in a *.Custom.cs file.
// Foundry never overwrites *.Custom.cs.
//
#nullable enable
";

        /// <summary>
        /// Header prepended to scaffold files, which Foundry writes once and then never touches.
        /// </summary>
        public const string ScaffoldHeader =
@"// <foundry-scaffold/>
//
// Foundry generated this file once as a starting point and will never overwrite it.
// This is your file: put your business logic here and commit it.
//
#nullable enable
";

        private static readonly Regex IdentifierPattern =
            new(@"^[A-Za-z_][A-Za-z0-9_]*$", RegexOptions.Compiled | RegexOptions.CultureInvariant);

        // Attribute argument list: comma-separated integers, decimals, booleans, or
        // double-quoted strings containing no quote, backslash or brace.
        private static readonly Regex AttributeArgsPattern =
            new(@"^\s*(?:(?:-?\d+(?:\.\d+)?|true|false|""[^""\\{}]*"")\s*,\s*)*(?:-?\d+(?:\.\d+)?|true|false|""[^""\\{}]*"")\s*$",
                RegexOptions.Compiled | RegexOptions.CultureInvariant);

        private static readonly Regex AttributeCallPattern =
            new(@"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", RegexOptions.Compiled | RegexOptions.Singleline);

        /// <summary>
        /// The full set of C# reserved keywords. A schema name matching one of these cannot be
        /// emitted as an identifier.
        /// </summary>
        public static readonly IReadOnlySet<string> ReservedKeywords = new HashSet<string>(StringComparer.Ordinal)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
            "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
            "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
            "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
            "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
            "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw",
            "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using",
            "virtual", "void", "volatile", "while"
        };

        /// <summary>
        /// Returns true when <paramref name="name"/> is a valid, non-reserved C# identifier.
        /// </summary>
        public static bool IsValidIdentifier(string? name)
            => !string.IsNullOrEmpty(name)
               && IdentifierPattern.IsMatch(name)
               && !ReservedKeywords.Contains(name);

        /// <summary>
        /// Returns true when <paramref name="ns"/> is a valid dot-separated C# namespace.
        /// </summary>
        public static bool IsValidNamespace(string? ns)
            => !string.IsNullOrEmpty(ns)
               && ns.Split('.').All(IsValidIdentifier);

        /// <summary>
        /// Validates a value destined for an identifier position and returns it unchanged.
        /// </summary>
        /// <exception cref="UnsafeSchemaValueException">
        /// The value is not a valid, non-reserved C# identifier.
        /// </exception>
        public static string Ident(string? name, string what = "name")
        {
            if (string.IsNullOrEmpty(name))
                throw new UnsafeSchemaValueException(DiagnosticCatalog.InvalidIdentifier, $"Empty {what}.");

            if (ReservedKeywords.Contains(name))
                throw new UnsafeSchemaValueException(DiagnosticCatalog.ReservedKeyword, $"{what} '{name}' is a reserved C# keyword.");

            if (!IdentifierPattern.IsMatch(name))
                throw new UnsafeSchemaValueException(DiagnosticCatalog.InvalidIdentifier, $"{what} '{name}' is not a valid C# identifier.");

            return name;
        }

        /// <summary>
        /// Validates a value destined for a namespace position and returns it unchanged.
        /// </summary>
        /// <exception cref="UnsafeSchemaValueException">The value is not a valid C# namespace.</exception>
        public static string Ns(string? ns)
        {
            if (!IsValidNamespace(ns))
                throw new UnsafeSchemaValueException(DiagnosticCatalog.InvalidNamespace, $"'{ns}' is not a valid C# namespace.");

            return ns!;
        }

        /// <summary>
        /// Escapes a value for emission inside a regular (non-verbatim) C# string literal.
        /// </summary>
        /// <remarks>
        /// The returned text is literal <em>content</em> only; the caller supplies the quotes.
        /// Generator templates are verbatim interpolated strings, so a call site looks like
        /// <c>$@"Topic =&gt; ""{CodeGen.Lit(topic)}"";"</c> — the doubled quotes render as the
        /// literal's delimiters and this method makes the content safe between them.
        /// </remarks>
        public static string Lit(string? value)
        {
            if (string.IsNullOrEmpty(value)) return string.Empty;

            var sb = new StringBuilder(value!.Length + 8);
            foreach (var c in value)
            {
                switch (c)
                {
                    case '\\': sb.Append("\\\\"); break;
                    case '"': sb.Append("\\\""); break;
                    case '\r': sb.Append("\\r"); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\t': sb.Append("\\t"); break;
                    case '\0': sb.Append("\\0"); break;
                    default:
                        // Control characters would produce an unterminated or malformed literal.
                        if (char.IsControl(c))
                            sb.Append("\\u").Append(((int)c).ToString("x4"));
                        else
                            sb.Append(c);
                        break;
                }
            }
            return sb.ToString();
        }

        /// <summary>
        /// Emits a quoted C# string literal for <paramref name="value"/>, or <c>null</c>
        /// when the value is null.
        /// </summary>
        public static string LitOrNull(string? value)
            => value is null ? "null" : $"\"{Lit(value)}\"";

        /// <summary>
        /// Emits a C# collection initialiser of string literals.
        /// </summary>
        public static string LitList(IEnumerable<string>? values)
            => string.Join(", ", (values ?? Enumerable.Empty<string>()).Select(v => $"\"{Lit(v)}\""));

        /// <summary>
        /// Emits a C# boolean literal.
        /// </summary>
        public static string Bool(bool value) => value ? "true" : "false";

        /// <summary>
        /// Parses a schema attribute of the form <c>Name</c> or <c>Name(args)</c> and validates
        /// that it is safe to emit.
        /// </summary>
        /// <param name="attribute">The raw attribute text from the schema.</param>
        /// <param name="name">The attribute name, when parsing succeeds.</param>
        /// <param name="args">
        /// The argument list without surrounding parentheses, or an empty string for a bare
        /// attribute. Guaranteed to contain only numbers, booleans and simple quoted strings.
        /// </param>
        /// <returns>
        /// True when the attribute is well-formed and safe. False means the caller must reject
        /// it — never emit an attribute this method declined.
        /// </returns>
        /// <remarks>
        /// This exists because the previous emitter passed attributes such as
        /// <c>MinLength(5)</c> straight into <c>[{attr}]</c>. That let any schema value become
        /// arbitrary C#: an attribute of <c>X)] public class Evil {{ }} [Obsolete(</c> would
        /// close the attribute and open a new type declaration.
        /// </remarks>
        public static bool TryParseAttribute(string? attribute, out string name, out string args)
        {
            name = string.Empty;
            args = string.Empty;

            if (string.IsNullOrWhiteSpace(attribute)) return false;

            var text = attribute!.Trim();

            // Bare attribute, e.g. "Required".
            if (!text.Contains('('))
            {
                if (!IsValidIdentifier(text)) return false;
                name = text;
                return true;
            }

            var match = AttributeCallPattern.Match(text);
            if (!match.Success) return false;

            var candidateName = match.Groups[1].Value;
            var candidateArgs = match.Groups[2].Value;

            if (!IsValidIdentifier(candidateName)) return false;
            if (!AttributeArgsPattern.IsMatch(candidateArgs)) return false;

            name = candidateName;
            args = candidateArgs.Trim();
            return true;
        }

        /// <summary>
        /// Indents every line of <paramref name="text"/> by <paramref name="spaces"/> columns.
        /// </summary>
        public static string Indent(string text, int spaces)
        {
            var pad = new string(' ', spaces);
            return string.Join("\n", text.Split('\n').Select(l => string.IsNullOrEmpty(l) ? l : pad + l));
        }

        /// <summary>
        /// Processes a string for safe XML documentation emission as a summary element.
        /// </summary>
        /// <param name="text">The raw text to process.</param>
        /// <param name="indentSpaces">Number of spaces to indent all output lines (0 or more).</param>
        /// <returns>XML-escaped and properly formatted documentation comment, or string.Empty for invalid input.</returns>
        /// <remarks>
        /// Tabs within descriptions are preserved as-is. While tabs render unpredictably in XML comments
        /// depending on the viewer, stripping them would lose information the author deliberately included.
        /// </remarks>
        public static string XmlDoc(string? text, int indentSpaces = 0)
        {
            // Return empty for null, empty, or whitespace-only input
            if (string.IsNullOrWhiteSpace(text))
                return string.Empty;

            // Split on newline sequences FIRST: \r\n, \r, then \n
            // This must happen before control-character stripping so newlines aren't consumed
            var lines = text!.Replace("\r\n", "\n").Replace("\r", "\n").Split('\n');

            // Strip C0 control characters (except tab) from each line
            string StripControls(string line)
            {
                var sb = new StringBuilder();
                foreach (var c in line)
                {
                    // Keep printable chars (>=32), tab (9), and newlines (already split, so won't appear here)
                    if (c >= 32 || c == '\t')
                        sb.Append(c);
                }
                return sb.ToString();
            }

            // Escape XML special characters: & first, then < and >
            string EscapeXml(string s)
            {
                return s.Replace("&", "&amp;")
                        .Replace("<", "&lt;")
                        .Replace(">", "&gt;");
            }

            // Prepare indentation prefix
            var indent = new string(' ', indentSpaces);
            var commentPrefix = $"{indent}/// ";

            // Build the summary content with control-stripped and XML-escaped text on each line
            var linesOutput = new List<string>();
            foreach (var line in lines)
            {
                var cleaned = StripControls(line);
                linesOutput.Add(commentPrefix + EscapeXml(cleaned));
            }

            // Wrap with <summary> and </summary>
            var startSummary = $"{commentPrefix}<summary>";
            var endSummary = $"{commentPrefix}</summary>";

            // Join all parts, ensuring trailing newline
            return string.Join("\n", new[] { startSummary }.Concat(linesOutput).Append(endSummary)) + "\n";
        }
    }
}
