/**
 * Client for everything the C# compiler derives.
 *
 * The manifest is derived from the IR by the C# compiler's `ApiManifestGenerator`, which is the single
 * producer of that contract. Studio used to compute it here by walking the canvas, and the two
 * implementations disagreed: this one emitted `/api/v1/{plural}` where the compiler emits
 * `/api/{plural}`, and it gave an entity with no declared methods a full CRUD surface where the
 * compiler skips it. An application therefore served different URLs depending on which tool wrote its
 * manifest, and nothing reported the conflict because each manifest was individually valid.
 *
 * Asking the backend costs a round trip and requires it to be running. That is the intended trade: a
 * clear error is better than silently handing someone a manifest that does not match what
 * `foundry compile` would produce.
 */

/** Base URL of the Foundry Studio backend. */
export const BACKEND_URL = 'http://localhost:5100';

/**
 * Derives the manifest for `schema` via the backend.
 *
 * @throws Error when the backend is unreachable or rejects the schema. Callers should surface the
 * message rather than falling back to a locally-computed manifest — a fallback would reintroduce
 * exactly the divergence this replaced.
 */
export async function deriveApiManifest(schema: unknown): Promise<string> {
  let response: Response;
  try {
    response = await fetch(`${BACKEND_URL}/api/manifest`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(schema),
    });
  } catch {
    throw new Error(
      `Could not reach the Foundry backend at ${BACKEND_URL}. ` +
        'The API manifest is generated by the compiler, so the backend must be running.',
    );
  }

  if (!response.ok) {
    const detail = await response.text().catch(() => '');
    throw new Error(
      `The backend could not generate the API manifest (${response.status} ${response.statusText})` +
        (detail ? `: ${detail}` : ''),
    );
  }

  return response.text();
}

/**
 * The CRUD route the compiler will generate for `entityName`.
 *
 * Mirrors `ApiManifestGenerator.RouteFor` in the C# compiler, which is the authority. This exists only
 * for *display* — the API designer and playground need a route without a server round trip per
 * keystroke — and is pinned to the compiler's behaviour by a test table shared with
 * `ApiManifestGeneratorTests`.
 *
 * It replaces three separate derivations in the UI, all of which were wrong: two emitted an
 * `/api/v1/` prefix the compiler does not use, and the playground did not pluralise at all, so it sent
 * requests to `/api/v1/customer` while the running application served `/api/customers`. Nothing
 * reported that; the request simply 404'd and looked like a broken application.
 *
 * A mirrored function is a weaker guarantee than a single implementation. It is the trade for keeping
 * the editor responsive and offline, and the shared test table is what keeps it honest.
 */
export function crudRouteFor(entityName: string): string {
  if (!entityName) return '/api';
  return `/api/${pluralize(entityName).toLowerCase()}`;
}

/** Minimal English pluraliser, matching `ApiManifestGenerator.Pluralize`. */
function pluralize(word: string): string {
  if (!word) return word;

  const lower = word.toLowerCase();

  // "Category" -> "Categories", but "Day" -> "Days".
  if (lower.length > 1 && lower.endsWith('y') && !'aeiou'.includes(lower[lower.length - 2])) {
    return `${word.slice(0, -1)}ies`;
  }

  if (['s', 'x', 'z', 'ch', 'sh'].some((suffix) => lower.endsWith(suffix))) {
    return `${word}es`;
  }

  return `${word}s`;
}

/**
 * Compiles `schema` to C# through the compiler, returning a filename-to-source map.
 *
 * Replaces four hand-written TypeScript generators in `StudioWorkspace` that reimplemented
 * `PocoGenerator` for entities, enums, DTOs and handlers. They had drifted in ways that made the
 * preview actively misleading rather than merely stale:
 *
 * - They emitted `using FoundryMongo.Domain.Entities;`, a namespace that does not exist — the compiler
 *   emits `Foundry.Core.Entities`. The previewed code would not compile.
 * - They omitted `partial`, which the entire scaffold-preservation design depends on: a developer
 *   copying the preview loses the `*.Custom.cs` extension point silently.
 * - They omitted the generated-file header, `#nullable enable`, validation attributes, `[JsonIgnore]`
 *   on soft-delete fields, compound indexes and workflow interfaces.
 *
 * A preview that differs from what `foundry compile` produces is worse than no preview, because it is
 * read as the output. There is now one generator.
 */
export async function compileToCs(schema: unknown): Promise<Record<string, string>> {
  let response: Response;
  try {
    response = await fetch(`${BACKEND_URL}/api/compile`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(schema),
    });
  } catch {
    throw new Error(
      `Could not reach the Foundry backend at ${BACKEND_URL}. ` +
        'C# is generated by the compiler, so the backend must be running to preview it.',
    );
  }

  if (!response.ok) {
    const detail = await response.text().catch(() => '');
    throw new Error(
      `The compiler rejected the schema (${response.status} ${response.statusText})` +
        (detail ? `: ${detail}` : ''),
    );
  }

  const payload = (await response.json()) as { files?: Record<string, string> };
  const files = payload.files ?? {};

  // The compiler keys files by path without an extension -- "Customer", "Handlers/SubmitOrderHandler" --
  // and its own writer appends ".cs" when saving. The same is done here so the preview list and the
  // downloaded filenames match what `foundry compile` writes to disk; without it, downloads landed as
  // extensionless files.
  return Object.fromEntries(
    Object.entries(files).map(([path, source]) => [path.endsWith('.cs') ? path : `${path}.cs`, source]),
  );
}
