/**
 * Client for everything the C# compiler derives.
 *
 * The manifest is derived from the IR by the C# compiler's `ApiManifestGenerator`, which is the single
 * producer of that contract. Studio used to compute it here by walking the canvas, and the two
 * implementations disagreed: this one emitted `/api/v1/{plural}` where the compiler emits
 * `/api/{plural}`, and it gave an entity with no declared methods a full CRUD surface where the
 * compiler skips it. An application therefore served different URLs depending on which tool wrote its
 * manifest, and nothing reported the conflict because each manifest was individually valid.
 *
 * Asking the backend costs a round trip and requires it to be running. That is the intended trade: a
 * clear error is better than silently handing someone a manifest that does not match what
 * `foundry compile` would produce.
 */

/** Base URL of the Foundry Studio backend. */
export const BACKEND_URL = 'http://localhost:5100';

/**
 * Derives the manifest for `schema` via the backend.
 *
 * @throws Error when the backend is unreachable or rejects the schema. Callers should surface the
 * message rather than falling back to a locally-computed manifest — a fallback would reintroduce
 * exactly the divergence this replaced.
 */
export async function deriveApiManifest(schema: unknown): Promise<string> {
  let response: Response;
  try {
    response = await fetch(`${BACKEND_URL}/api/manifest`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(schema),
    });
  } catch {
    throw new Error(
      `Could not reach the Foundry backend at ${BACKEND_URL}. ` +
        'The API manifest is generated by the compiler, so the backend must be running.',
    );
  }

  if (!response.ok) {
    const detail = await response.text().catch(() => '');
    throw new Error(
      `The backend could not generate the API manifest (${response.status} ${response.statusText})` +
        (detail ? `: ${detail}` : ''),
    );
  }

  return response.text();
}

/** Entity name to the route the compiler generates for it. */
export type RouteMap = Readonly<Record<string, string>>;

/**
 * Reads the entity-to-route map out of a manifest the compiler produced.
 *
 * This replaces `crudRouteFor`, a TypeScript reimplementation of `ApiManifestGenerator.RouteFor` and
 * its pluraliser. That mirror was the last one left, kept because the designer and playground need a
 * route to display and a request per keystroke would be absurd. It was pinned by a test table
 * duplicated on the C# side — which catches a *changed* derivation and not a *new* rule, since a
 * shared table only tests the cases someone thought to write down twice.
 *
 * Routes are now read from a manifest the compiler derived and Studio cached, so there is one
 * implementation. Two consequences worth stating, because both are improvements rather than costs:
 *
 * - An entity that declares no methods has no route here, because the compiler generates none for it.
 *   The designer previously displayed a route for it anyway.
 * - With no manifest — the backend is down, or the schema has not been derived yet — a route is
 *   *unknown* rather than guessed. The playground refuses to send instead of calling a URL it made up.
 */
export function parseManifestRoutes(manifestJson: string): RouteMap {
  let manifest: unknown;
  try {
    manifest = JSON.parse(manifestJson);
  } catch {
    throw new Error('The backend returned a manifest that is not valid JSON.');
  }

  const endpoints = (manifest as { Endpoints?: unknown })?.Endpoints;
  if (!Array.isArray(endpoints)) return {};

  const routes: Record<string, string> = {};
  for (const endpoint of endpoints) {
    const entity = (endpoint as { Entity?: unknown })?.Entity;
    const route = (endpoint as { Route?: unknown })?.Route;

    if (typeof entity === 'string' && entity && typeof route === 'string' && route) {
      routes[entity] = route;
    }
  }

  return routes;
}

/**
 * Compiles `schema` to C# through the compiler, returning a filename-to-source map.
 *
 * Replaces four hand-written TypeScript generators in `StudioWorkspace` that reimplemented
 * `PocoGenerator` for entities, enums, DTOs and handlers. They had drifted in ways that made the
 * preview actively misleading rather than merely stale:
 *
 * - They emitted `using FoundryMongo.Domain.Entities;`, a namespace that does not exist — the compiler
 *   emits `Foundry.Core.Entities`. The previewed code would not compile.
 * - They omitted `partial`, which the entire scaffold-preservation design depends on: a developer
 *   copying the preview loses the `*.Custom.cs` extension point silently.
 * - They omitted the generated-file header, `#nullable enable`, validation attributes, `[JsonIgnore]`
 *   on soft-delete fields, compound indexes and workflow interfaces.
 *
 * A preview that differs from what `foundry compile` produces is worse than no preview, because it is
 * read as the output. There is now one generator.
 */
export async function compileToCs(schema: unknown): Promise<Record<string, string>> {
  let response: Response;
  try {
    response = await fetch(`${BACKEND_URL}/api/compile`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(schema),
    });
  } catch {
    throw new Error(
      `Could not reach the Foundry backend at ${BACKEND_URL}. ` +
        'C# is generated by the compiler, so the backend must be running to preview it.',
    );
  }

  if (!response.ok) {
    const detail = await response.text().catch(() => '');
    throw new Error(
      `The compiler rejected the schema (${response.status} ${response.statusText})` +
        (detail ? `: ${detail}` : ''),
    );
  }

  const payload = (await response.json()) as { files?: Record<string, string> };
  const files = payload.files ?? {};

  // The compiler keys files by path without an extension -- "Customer", "Handlers/SubmitOrderHandler" --
  // and its own writer appends ".cs" when saving. The same is done here so the preview list and the
  // downloaded filenames match what `foundry compile` writes to disk; without it, downloads landed as
  // extensionless files.
  return Object.fromEntries(
    Object.entries(files).map(([path, source]) => [path.endsWith('.cs') ? path : `${path}.cs`, source]),
  );
}
