using System.Text;
using Foundry.Schema.Compiler;
using Xunit;

namespace Foundry.Schema.Compiler.Tests;

/// <summary>
/// Covers what a recompile deletes from the output directory, and — mostly — what it does not.
/// </summary>
/// <remarks>
/// These drive <see cref="Program.Main"/> rather than a generator, because pruning is a property of
/// the compile as a whole: what survives depends on what this run emitted. Every case that matters
/// here is a deletion, so the ones asserting a file is still present are the point of the suite.
/// </remarks>
public class PruneOrphansTests : IDisposable
{
    private readonly string _work;
    private readonly string _out;
    private readonly string _schema;

    public PruneOrphansTests()
    {
        _work = Path.Combine(Path.GetTempPath(), "foundry-prune-" + Guid.NewGuid().ToString("N"));
        _out = Path.Combine(_work, "Generated");
        _schema = Path.Combine(_work, "schema.json");
        Directory.CreateDirectory(_out);
        File.WriteAllText(_schema, SchemaWith("Alpha", "Beta"));
    }

    public void Dispose()
    {
        if (Directory.Exists(_work)) Directory.Delete(_work, recursive: true);
        GC.SuppressFinalize(this);
    }

    private static string SchemaWith(params string[] entityNames)
    {
        var entities = entityNames.Select(n => $@"
            {{
              ""name"": ""{n}"",
              ""apiEnabledMethods"": [""GET""],
              ""apiBusinessRules"": {{ ""GET"": [""{n}Rule""] }},
              ""properties"": [
                {{ ""name"": ""Id"", ""type"": ""ObjectId"", ""isKey"": true }},
                {{ ""name"": ""Name"", ""type"": ""string"" }}
              ]
            }}");

        return $@"{{ ""namespace"": ""Prune.Test"", ""entities"": [{string.Join(",", entities)}] }}";
    }

    private int Compile(params string[] extra)
    {
        var args = new List<string> { "--input", _schema, "--output", _out };
        args.AddRange(extra);
        return Program.Main(args.ToArray());
    }

    private string Path_(params string[] parts) => Path.Combine(new[] { _out }.Concat(parts).ToArray());

    [Fact]
    public void AFileTheSchemaNoLongerEmitsIsRemoved()
    {
        Assert.Equal(0, Compile());
        Assert.True(File.Exists(Path_("Entities", "Beta.cs")));

        // Beta leaves the schema. Its record used to stay behind, compiling and wired to nothing.
        File.WriteAllText(_schema, SchemaWith("Alpha"));
        Assert.Equal(0, Compile());

        Assert.False(File.Exists(Path_("Entities", "Beta.cs")));
        Assert.True(File.Exists(Path_("Entities", "Alpha.cs")));
    }

    [Fact]
    public void AScaffoldIsNeverRemoved_EvenWhenNoLongerEmitted()
    {
        Assert.Equal(0, Compile());

        var scaffold = Path_("Rules", "BetaRule.cs");
        Assert.True(File.Exists(scaffold));
        File.AppendAllText(scaffold, "\n// the policy a schema cannot state\n");

        File.WriteAllText(_schema, SchemaWith("Alpha"));
        Assert.Equal(0, Compile());

        // The entity went; the business logic written against it did not. It will stop compiling,
        // which is loud and recoverable -- deleting it silently would not be.
        Assert.True(File.Exists(scaffold));
        Assert.Contains("the policy a schema cannot state", File.ReadAllText(scaffold));
    }

    [Fact]
    public void ACustomPartialIsNeverRemoved()
    {
        Assert.Equal(0, Compile());

        // The place the generated header itself tells developers to put their code.
        var custom = Path_("Alpha.Custom.cs");
        File.WriteAllText(custom, "public partial record Alpha { public string Extra => \"x\"; }");

        Assert.Equal(0, Compile());

        Assert.True(File.Exists(custom));
    }

    [Fact]
    public void AFileTheCompilerDidNotWriteIsNeverRemoved()
    {
        Assert.Equal(0, Compile());

        // No marker, so this compiler has no evidence it produced the file and no business
        // deleting it -- however little it belongs in an output directory.
        var stray = Path_("Handwritten.cs");
        File.WriteAllText(stray, "public class Handwritten { }");

        Assert.Equal(0, Compile());

        Assert.True(File.Exists(stray));
    }

    [Fact]
    public void OnlyGeneratedFilesAreRemoved_IdentifiedByTheirMarker()
    {
        Assert.Equal(0, Compile());

        // Byte-for-byte real compiler output, in a location this schema does not emit: the shape
        // left behind by a change to the emit layout.
        var orphan = Path_("Beta.cs");
        File.Copy(Path_("Entities", "Beta.cs"), orphan);
        Assert.StartsWith("// <auto-generated/>", File.ReadAllText(orphan), StringComparison.Ordinal);

        Assert.Equal(0, Compile());

        Assert.False(File.Exists(orphan));
    }

    [Fact]
    public void NoPruneKeepsOrphans()
    {
        Assert.Equal(0, Compile());
        var orphan = Path_("Beta.cs");
        File.Copy(Path_("Entities", "Beta.cs"), orphan);

        Assert.Equal(0, Compile("--no-prune"));

        Assert.True(File.Exists(orphan));
    }

    [Fact]
    public void ADirectoryLeftEmptyByPruningIsRemoved()
    {
        Assert.Equal(0, Compile());

        var staleDir = Path_("Kafka");
        Directory.CreateDirectory(staleDir);
        File.Copy(Path_("Entities", "Beta.cs"), Path.Combine(staleDir, "BetaKafkaConsumer.cs"));

        Assert.Equal(0, Compile());

        Assert.False(Directory.Exists(staleDir));
    }

    [Fact]
    public void ADirectoryHoldingSomethingKeptSurvives()
    {
        Assert.Equal(0, Compile());

        var dir = Path_("Kafka");
        Directory.CreateDirectory(dir);
        File.Copy(Path_("Entities", "Beta.cs"), Path.Combine(dir, "BetaKafkaConsumer.cs"));
        File.WriteAllText(Path.Combine(dir, "notes.md"), "keep me");

        Assert.Equal(0, Compile());

        Assert.True(Directory.Exists(dir));
        Assert.True(File.Exists(Path.Combine(dir, "notes.md")));
        Assert.False(File.Exists(Path.Combine(dir, "BetaKafkaConsumer.cs")));
    }

    [Fact]
    public void AFailedCompileRemovesNothing()
    {
        Assert.Equal(0, Compile());

        var orphan = Path_("Beta.cs");
        File.Copy(Path_("Entities", "Beta.cs"), orphan);

        // An entity with no key: rejected by the validator, so nothing is written -- and nothing
        // may be deleted either. Pruning against a schema that did not compile would clear an
        // output directory on a typo.
        File.WriteAllText(_schema,
            @"{ ""namespace"": ""Prune.Test"", ""entities"": [ { ""name"": ""Alpha"", ""properties"": [] } ] }");
        Assert.Equal(1, Compile());

        Assert.True(File.Exists(orphan));
        Assert.True(File.Exists(Path_("Entities", "Alpha.cs")));
    }
}
